# Generated by Django 4.2.3 on 2023-08-10 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_noticia_imagen_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='fecha_publicacion',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='contenido',
            new_name='texto',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='autor',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='posts.noticia'),
        ),
    ]
