# Generated by Django 4.2.3 on 2023-08-10 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_fecha_publicacion_comentario_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='usuario',
            new_name='autor',
        ),
    ]
